# SPDX-FileCopyrightText: 2025 Sebastian Küthe and (other) contributors to project grafana-oss-team-sync <https://github.com/skuethe/grafana-oss-team-sync>
# SPDX-License-Identifier: GPL-3.0-or-later

services:
  grafana:
    image: docker.io/grafana/grafana-oss:latest@sha256:83749231c3835e390a3144e5e940203e42b9589761f20ef3169c716e734ad505
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'


  devproxy:
    image: ghcr.io/dotnet/dev-proxy:2.3.0@sha256:e06ccef47344151e8c874767c8e0f1d3eb888451d635585a7c5e26fbbc214cb8
    container_name: devproxy
    ports:
    - '8000:8000'
    - '8897:8897'
    command:
    # For recording mock data, use modified dev proxy config
    - '--config-file'
    - '/config/entraid-record.json'
    volumes:
      # For recording mock data, mount with write access
      - '../test/devproxy/configs:/config:Z'
      - '../test/devproxy/cert:/home/devproxy/.config/dev-proxy/rootCert:Z'
